# Generated by Django 5.1.4 on 2024-12-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_date_of_birth_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='check_in_cycle_length',
            field=models.CharField(choices=[('12h', '12 hours'), ('1D', '1 day (24 hours)'), ('2D', '2 days (48 hours)'), ('3D', '3 days (72 hours)'), ('5D', '5 days'), ('1W', '1 week (7 days)')], default='2D', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='currently_working_on',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests_description',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_description',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='visible_to_search',
            field=models.BooleanField(default=False),
        ),
    ]
