# Generated by Django 5.1.4 on 2024-12-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_blocked_profile_do_not_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_followers_list',
            field=models.BooleanField(default=False),
        ),
    ]
