# Generated by Django 5.1.4 on 2024-12-29 01:34

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
