INDUSTRIES = [
    ("technology", "Technology"),
    ("finance", "Finance"),
    ("healthcare", "Healthcare"),
    ("education", "Education"),
    ("manufacturing", "Manufacturing"),
    ("retail", "Retail"),
    ("hospitality", "Hospitality"),
    ("real_estate", "Real Estate"),
    ("construction", "Construction"),
    ("transportation", "Transportation"),
    ("energy", "Energy"),
    ("agriculture", "Agriculture"),
    ("media", "Media"),
    ("entertainment", "Entertainment"),
    ("legal", "Legal"),
    ("consulting", "Consulting"),
    ("insurance", "Insurance"),
    ("advertising", "Advertising"),
    ("public_relations", "Public Relations"),
    ("nonprofit", "Nonprofit"),
    ("government", "Government"),
    ("telecommunications", "Telecommunications"),
    ("automotive", "Automotive"),
    ("aerospace", "Aerospace"),
    ("biotechnology", "Biotechnology"),
    ("pharmaceutical", "Pharmaceutical"),
    ("food_and_beverage", "Food & Beverage"),
    ("fashion", "Fashion"),
    ("arts_and_culture", "Arts & Culture"),
    ("sports", "Sports"),
    ("gaming", "Gaming"),
    ("travel_and_tourism", "Travel & Tourism"),
    ("ecommerce", "E-commerce"),
    ("cybersecurity", "Cybersecurity"),
    ("artificial_intelligence", "Artificial Intelligence"),
    ("blockchain", "Blockchain"),
    ("environmental_services", "Environmental Services"),
    ("mining", "Mining"),
    ("marine", "Marine"),
    ("education_technology", "Education Technology"),
    ("event_management", "Event Management"),
    ("supply_chain", "Supply Chain"),
    ("human_resources", "Human Resources"),
    ("printing_and_publishing", "Printing & Publishing"),
    ("venture_capital", "Venture Capital"),
    ("private_equity", "Private Equity"),
    ("investment_banking", "Investment Banking"),
    ("agritech", "AgriTech"),
    ("proptech", "PropTech"),
    ("cleantech", "CleanTech"),
    ("logistics", "Logistics"),
    ("fitness_and_wellness", "Fitness & Wellness"),
    ("home_and_garden", "Home & Garden"),
    ("personal_care", "Personal Care"),
    ("petcare", "Petcare"),
    ("luxury_goods", "Luxury Goods"),
    ("space_technology", "Space Technology"),
    ("nanotechnology", "Nanotechnology"),
    ("robotics", "Robotics"),
    ("hardware", "Hardware"),
    ("software", "Software"),
    ("venture_building", "Venture Building"),
    ("shared_economy", "Shared Economy"),
    ("social_enterprise", "Social Enterprise"),
    ("research_and_development", "Research & Development"),
    ("esports", "Esports"),
    ("fine_arts", "Fine Arts"),
    ("consumer_electronics", "Consumer Electronics"),
    ("home_appliances", "Home Appliances"),
    ("aviation", "Aviation"),
    ("chemical", "Chemical"),
    ("defense", "Defense"),
    ("nonprofit_tech", "Nonprofit Tech"),
    ("startup_acceleration", "Startup Acceleration"),
]
