# Generated by Django 5.1.4 on 2024-12-23 21:48

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_article_likes_article_saves_article_shares_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.TextField(blank=True, null=True, validators=[content.models.Article.validate_subtitle_length]),
        ),
    ]
