# Generated by Django 5.1.4 on 2024-12-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_article_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(default='media/default_article_feature_img.webp', upload_to='media/featured_images'),
        ),
    ]
