# Generated by Django 5.1.4 on 2024-12-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_article_hide_likes_counts_article_hide_shares_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='-'),
        ),
    ]
