# Generated by Django 5.1.4 on 2025-01-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(default='-', editable=False, max_length=450),
        ),
    ]
