# Generated by Django 5.1.4 on 2024-12-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_article_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(default='-', editable=False, max_length=450),
        ),
    ]
